name: Deploy to Production

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    container:
      image: azionedge/centos-go
    env:
      CGO_ENABLED: 0 # Statically linked

    steps:
      - name: Setting GIT
        run: git config --global url."https://${{ secrets.GLOBAL_TOKEN }}:x-oauth-basic@github.com/aziontech".insteadOf "https://github.com/aziontech"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: tag_ver
        uses: anothrNick/github-tag-action@master
        env:
          RELEASE_BRANCHES: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Refresh git
        run: git fetch --tags

