name: Generate docs and upload to wiki

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - docs-to-wiki

jobs:
  build:
    runs-on: self-hosted
    container:
      image: golang:1.17
    env:
      CGO_ENABLED: 0 # Statically linked

    steps:
      - name: Setting GIT
        run: git config --global url."https://${{ secrets.GLOBAL_TOKEN }}:x-oauth-basic@github.com/aziontech".insteadOf "https://github.com/aziontech"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: ${{github.repository}}.wiki

      - name: Generate docs
        run: |
          echo $pwd
          go run pkg/gen_docs/main.go --file-type "md" --doc-path "./docs"

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add changes"

      - name: Push changes to wiki repo
        uses: ad-m/github-push-action@master
        with:
          repository: ${{github.repository}}.wiki
          github_token: ${{ secrets.GITHUB_TOKEN }}

