name: Generate docs and upload to wiki

on:
  workflow_dispatch:
  push:
    branches:
      - test-webhook

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.17
    env:
      CGO_ENABLED: 0 # Statically linked

    steps:
      - name: Setting GIT
        run: git config --global url."https://${{ secrets.GLOBAL_TOKEN }}:x-oauth-basic@github.com/aziontech".insteadOf "https://github.com/aziontech"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate docs
        run: go run ./cmd/gen_docs/main.go --file-type "md" --doc-path "/tmp/docs"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: ${{github.repository}}.wiki

      - name: Copy files
        run: cp /tmp/docs/* .

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add changes"
          git push

  send_webhook:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Setup Env
        run: apt-get update && apt-get install -y curl docker 
        shell: bash

      - name: Clean up
        run: docker run --rm --volume "`pwd`:/app" --workdir "/app" alpine:3.13 find . -delete

      - name: Fix permissions
        run: docker run --rm --volume "`pwd`:/app" --workdir "/app" alpine:3.13 chmod -R a+rw .

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract PR Information
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          commit_message="${{ github.event.head_commit.message }}"
          echo "1. $commit_message"
          commit_message="${commit_message/Merge pull request #/}"
          echo "2. $commit_message"
          pr_number="${commit_message%% *}"
          echo "3. $pr_number"
          content=$(gh pr view $pr_number --json title,body --jq '.title,.body')

          echo $content

          curl -X POST \
            -H 'Content-Type: application/json' \
            -d "{ \"text\": \"$content\"}" \
            https://hooks.slack.com/services/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
