name: Test and Build

on:
  pull_request:
    types: [opened, synchronize]
    branches-ignore:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setting GIT
        run: git config --global url."https://${{ secrets.GLOBAL_TOKEN }}:x-oauth-basic@github.com/aziontech".insteadOf "https://github.com/aziontech"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'
          check-latest: true

      - name: Install dependencies
        run: |
          go version
          go install golang.org/x/lint/golint
          go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Build & Test
        run: make test build

      - name: Linter
        run: make lint

      - name: Gosec
        run: make sec
