name: Deploy to Production

on:
  workflow_dispatch:
  push:
    branches:
      - workflow

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.20
    outputs:
      binver: ${{ steps.binversion.outputs.BIN_VERSION }}
    env:
      CGO_ENABLED: 0 # Statically linked

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setting up a secure repository
        run: git config --global --add safe.directory /__w/azion/azion

      - id: binversion 
        run: echo "BIN_VERSION=$(git describe --tags)" >> $GITHUB_OUTPUT
          
  bump_formula:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - run: echo `${{needs.build.outputs.binver}}


