name: Deploy to Production

on:
  workflow_dispatch:
  push:
    branches:
      - workflow

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.20
    outputs:
      binver: ${{ steps.binversion.outputs.BIN_VERSION }}
    env:
      CGO_ENABLED: 0 # Statically linked

    steps:

      - id: binversion 
        run: echo "BIN_VERSION=$(git describe --tags)" >> $GITHUB_OUTPUT
          
  bump_formula:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - run: echo `${{needs.build.outputs.binver}}


